### ISSUE TITLE
Qun buy

### ISSUE THREAD

**Issue by Aleksei-Droganov** [raspy135/Qun-synthesizer#1]
Hello, very interested with this synth. How could I buy it and could I work this synth such as complete hardware synth with other stuff? Thank you

**Comment by raspy135** [comment]
Hi Aleksei,

To purchase, I put shop link in the manual.
The link is https://shop.nunomo.com/products/qun-pocket-synthesizer

The synth has MIDI in/out, and BLE MIDI (for iOS / MAC). Please check "Connections" section in the manual for detail.
You can control all parameters of the synth through MIDI. All parameters are MIDI CC.
It can take MIDI clock or Sync clocks.
Let me know if you have any other questions.

**Comment by raspy135** [comment]
I will close this, please reopen it if you have other questions.
