### ISSUE TITLE
Qun doesn't receive midi

### ISSUE THREAD

**Issue by Djnro1** [raspy135/Qun-synthesizer#10]
Hi!

My Qun's midi in is plugged via trs to din cable to my soundcard's midi out.  My soundcard is a PreSonus Audiobox 44 VSL. I run Ableton Live 10 on a Windows 10 PC. I'm on Qun's firmware 1,65. I can play it fine with the Play Piano function but it doesn't respond to midi... I tried the Mode button to be sure that it receive midi and I'm on the right midi channel. What could be wrong? Please help!

Thanks in advance!

**Comment by Djnro1** [comment]
One note: when I plug the midi out of my soundcard to any of my other synths, they receive midi messages. Might it be a problem with my TRS to midi cable? If so, do you have a cable to recommend?

**Comment by raspy135** [comment]
Hi, what kind of adapter are you using?
At least you should see a square indicator at the top-left corner in the display.

Unfortunately, there are two types of TRS-MIDI adapter and they are not compatible.

Type A adapter is used by Korg, Line6 and make noise , and Qun uses type A. Type A is the standard defined by MIDI organization later.

Type B adapter is used by Arturia and I think Novation. 

The difference is channel connection(L/R is swapped). So technically somehow you can swap the channel it may work.
MIDI adapter for Korg something like https://www.amazon.com/MIDI-Cable-Line-6-Littlebits-Noise/dp/B0797SG8RS
If the description says "for Korg" or Line 6, IK Multimedia, then it will work. Do not buy if it doesn't say any specific brand, or saying incompatible brands.

**Comment by raspy135** [comment]
Here is more completed information about the MIDI-TRS adapter. Qun uses "TRS MIDI A"
https://www.midi.org/midi-articles/updated-how-to-make-your-own-3-5mm-mini-stereo-trs-to-midi-5-pin-din-cables

**Comment by Djnro1** [comment]
That's it: the one I bought is a type B... Thanks!

**Comment by raspy135** [comment]
I will close this issue, please reopen it if you have any following questions.

**Comment by Djnro1** [comment]
Thanks
