### ISSUE TITLE
Screen doesn't lit up anymore since 2.0 firmware update

### ISSUE THREAD

**Issue by Djnro1** [raspy135/Qun-synthesizer#11]
Hi!

I tried installing the 2.0 firmware following the instructions on the website this morning but I faced a problem. I was able to upgrade it in the past with success. When I was in the last step and pressed RST to reboot the unit, nothing happened. Tried multiple times. I then proceeded to unplug and replug the unit which, I guess, was an error? Now the screen of the unit doesn't lit up when I'm opening it. User error probably. Please help! Thanks in advance!

**Comment by Djnro1** [comment]
If there's no cure and I've messed my unit too bad to find a way to fix it, just let me know.

**Comment by raspy135** [comment]
Hi Have you tried to rollback the firmware to 1.70?
Basically the firmware uploading mode is almost impossible to break. So you should be able to rollback the firmware unless you put wrong address to the address field.
I made a lot of changes for 2.0, so it is possible it has some bugs related to the saved data.
Please let me know the result with older firmware.

**Comment by Djnro1** [comment]
I tried rollback to 1.70 a second time today and it doesnt change a thing... The screen doesnt light up anymore. Sorry! I checked the COM adress in the device manager so it should be the right one. There seem to be a red light on the board which I dont remember being there...

**Comment by raspy135** [comment]
Is this the first time you tried the firmware update?
Did you put 0x230000 in the address field?
Are you using Windows or Mac? I'd like to know the log, or GUI response if you use Windows.

**Comment by Djnro1** [comment]
I've updated it succesfully about a month ago.  I did put 0x230000 in the adress field. I'm on Windows. Here are 2 print screens of the GUI of the Flash Download tool. I'm not sure it's what you want. If not, I would need more precisions. Thanks!
![RASPY print screen 2](https://user-images.githubusercontent.com/71855115/99608427-dc910400-29db-11eb-8a58-e3f6b7d9cc57.jpg)
![RASPY print screen](https://user-images.githubusercontent.com/71855115/99608429-dd299a80-29db-11eb-94d0-aa1bcb7b65e5.jpg)

**Comment by Djnro1** [comment]
Here's a better picture... 
![RASPY print screen 3](https://user-images.githubusercontent.com/71855115/99608630-4dd0b700-29dc-11eb-8983-2a0ca5a7a619.jpg)

**Comment by raspy135** [comment]
I don't see anything wrong here. What if you try to set BAUD rate to 115200?
If you are familiar with console apps such as PuTTY, you may see some error message when you connect to COM7 with 115200bps.
Normally any error of firmware update other than putting wrong address shouldn't break the software.

We can have a video call if you prefer. I will let you know if I come up anything else.

**Comment by Djnro1** [comment]
I tried with BAUD rate set to 115200 and I still get the same result. I'm not familiar with PuTTY, tried to get familiar but didn't understand a thing... Lol Sorry! As for a video call, I'm a french speaker. I understand English 100% but you might find it hard to understand me and I might have problems finding the right words. I thought about it: maybe the update have nothing to do with the screen not functionning. Maybe by replugging the unit, I shorted a circuit on the board. There's a blinking little red light close near the big green light. I also see a big red light further in the rear of the unit. Don't know if this helps.

**Comment by Djnro1** [comment]
![IMG_1128](https://user-images.githubusercontent.com/71855115/99692647-86ae7180-2a58-11eb-830b-62c358578454.JPG)

**Comment by raspy135** [comment]
Unfortunately, LEDs doesn't help much.
Other possibility is somehow you broke other part of memory.

You can try the following extra firmware pieces. 
Please be careful to write the firmware, the writing address (0x230000 is for main firmware) is different.

https://www.dropbox.com/s/1tpxd1i3jlyif26/partitions.bin?dl=0
Writing address : 0x8000 

https://www.dropbox.com/s/ipst4hkal3mld1c/bootloader.bin?dl=0
Writing address : 0x1000 

If you are not comfortable to try them or didn't work with the firmware, then let's set up the call. We can talk via chat. Video will help a lot to figure out the issue.

**Comment by Djnro1** [comment]
I tried the two extra firmware pieces with the right writing adresses and it doesn't work. I would be available for a video chat next monday after supper. I'm in Montreal, Canada: I don't know if we are in the same time zone...

**Comment by Djnro1** [comment]
I'll be available every evening next week starting Monday.

**Comment by raspy135** [comment]
I'm in California, PST. I think your timezone is EST, correct? How about 7:30am PST (10:30am EST) on Wednesday?

**Comment by Djnro1** [comment]
I can't : I'll be in a meeting at my work place at that hour... Be assured
we respect social distancing and keep the mask on.  Sorry!

**Comment by Djnro1** [comment]
My time zone is Est. What are your other availabilities?

**Comment by Djnro1** [comment]
Hello! Are you still there?

**Comment by raspy135** [comment]
Sorry I was busy with other things. When are you available next week?

**Comment by Djnro1** [comment]
Thank you for your answer! Next week I would be available Monday, Wednesday, Thursday and Friday after 4pm. It would also be possible Sunday the 13th all day long.

**Comment by raspy135** [comment]
Hi ok so let's do the session 5pm(EST, 2pm PST) on Wednesday. I will find a way to have video call. Probably on Google Hangouts. I will send you an invitation.

**Comment by raspy135** [comment]
May I get your email address? Please send an email to info@nunomo.com

**Comment by Djnro1** [comment]
Thank you! I'll be there. Is it better to do it on the computer on which
the Qun is plugged in or on another one on which I can do video? I only
have audio on the one it's plugged in.

**Comment by raspy135** [comment]
It's better if you can show something on Webcam.

**Comment by Djnro1** [comment]
Will do, thanks!

**Comment by Djnro1** [comment]
I have sent you my email address.

**Comment by Djnro1** [comment]
Haven't received an invite. Is it still working for you?
