### ISSUE TITLE
How to load patches?

### ISSUE THREAD

**Issue by nickcoyne** [raspy135/Qun-synthesizer#12]
Its not clear to me how to load patches onto the device from my Mac? Or to save patches from the device to my Mac?

**Comment by raspy135** [comment]
Hi, 
The patch is standard MIDI file, a sort of MIDI CC messages. Play the file on your computer and send the MIDI data to Sun synthesizer to load the patch file.
To save the patch, go system menu. There is save slots. If you want to export the patch data, press "Rec" button on the base board when you are in Param mode. It will dump MIDI CC messages. Record the MIDI messages to the computer or sequencer.

**Comment by nickcoyne** [comment]
I'm struggling with the "play the file" part. If I import the file into Ableton Live and play it (with output to the correct port), nothing happens. In fact it clears the sound/preset that I was on. What software should I use to send the midi?

**Comment by nickcoyne** [comment]
Finally found a tool to do this - Midikit from the app store.
