### ISSUE TITLE
Daughterboard revisions

### ISSUE THREAD

**Issue by IrregularShed** [raspy135/Qun-synthesizer#13]
Hi!

I'd like to build a QUN-alike on a breadboard, using the board schematic in the repository as a jumping off point. Having watched the [Starsky Carr review video](https://www.youtube.com/watch?v=QsnHaT9Xl84) I noticed that the daughterboard on his is a version 2.2 and has a tiny IC labelled U2 which isn't on the schematic, but photos of the board I found online are versions 2.0 and 2.1 and don't have this IC present.

Could you clarify what this is, and possibly update the schematic?

Also I'm assuming that J6 is used to literally stack boards (having seen another photo), is that correct?

(I'm not attempting to create and sell clones, don't worry! I'm just a hard-up nerd who likes to build things that make noises, like this nonsense...)
![20210128_125617](https://user-images.githubusercontent.com/190127/107761151-ccf73200-6d22-11eb-9530-1ff86418f1d4.jpg)

**Comment by raspy135** [comment]
Let me update the schematic, please wait. U2 is a logic buffer to increase the driving power of MIDI out. It's added because some MIDI equipment wants more current.
