### ISSUE TITLE
ipad controller app?

### ISSUE THREAD

**Issue by nickcoyne** [raspy135/Qun-synthesizer#14]
In your demo videos, you're controlling the Qun with an ipad app. What app is that? It looks like a pretty nice UI.

**Comment by raspy135** [comment]
The app called MIDI Designer. It's a bit expensive but it works.

**Comment by nickcoyne** [comment]
That looks awesome. Do you have a layout you can share?

**Comment by raspy135** [comment]
I'm not using the app anymore, so the layout is outdated. Unfortunately, I need to update the layout first if I share.

**Comment by nickcoyne** [comment]
ok, thanks.
