### ISSUE TITLE
What is the note priority when playing two Quns in polyphonic mono/duo?

### ISSUE THREAD

**Issue by GregCashin** [raspy135/Qun-synthesizer#15]
I’m loving the synth, and I’m curious if I were to buy another one how the note priority would work in polyphonic mono/duo modes, mostly duo as poly mono with two Quns seems straightforward. (or with three, although you mention polyphony is only fully tested on two Quns, if I remember correctly)

I’ve figured out the duophonic mode for a single Qun, but I would like to know how two Quns would react to a polyphonic midi input in those two modes!

Thanks!

**Comment by raspy135** [comment]
Hi Qun uses first note priority. First played note stays and the last note will be ignored.
For polyphonic mode, Device Index in System Setting menu needs to be configured. After that configuration is straight forward. I recommend Method B.
https://github.com/raspy135/Qun-synthesizer#polyphonic-setup

**Comment by GregCashin** [comment]
I'm sorry I am having trouble wording my question properly (I am not an expert on these things at all), but what I am trying to ask is when 2 QUN's are synced in polyphonic duo mode how do the 4 voices respond to individual key presses? (Not all 4 pressed at once). I only have 1 QUN (for now), so I am curious.

My understanding/experience with 1 QUN in duo mode is that the first key pressed triggers the gate/envelope for both oscillators, and sets the pitch for the first, and while holding that a second key press will change the pitch of the second osc. Releasing both a playing a different single note will trigger the gate for both oscillators again, and change the pitch of the first one, while the second remains at the same pitch it was at previously until a second key is pressed again while holding a first one.

So with 2 QUNs in polyphonic duo mode will the first key press trigger the gate for all 4 voices, or just the first 2 voices? And if just the first 2 voices, then will the second key press trigger the other 2 voices, or will it just set the pitch of the second voice from the first QUN (similar to when using one QUN in duo)? And then the 3rd key triggers the next 2 voices? Or does the second key trigger the next 2 voices and third key set the pitch of a secondary oscillator?

Again, I'm sorry about the wording of the question, I am struggling to read it myself, but I don't know how to say it better!!!! I know that pressing 4 keys at once will trigger all 4 voices, but I am curious about what happens when I press 1 key, 2 keys, or 3 keys in polyphonic duo mode.

Again, this synth is awesome, thank you for making it! I'm hoping to make some videos in the near future showing it off as there aren't enough people talking about it! I noticed you sold out, will you be restocking or are you moving to a different project? I hope you will restock!

**Comment by raspy135** [comment]
It seems your Duo mode setup is incomplete (The result is interesting though).
You need to assign EG2(=ENV2) for Osc2. "OSC2 ENV SEL" is the parameter (Button 5 in OSC Switches mode). By doing this you will get two voices with one device. Env 1 controls Osc1, Env2 controls Osc2.

With two or more devices, you have two options ("Mono/Duo/Poly" setting, button 7 in Key/Other menu)

1. "PolyMono" - 1 voice per device. The first note triggers two oscillators like "Mono" mode. The second note will trigger device index 2's oscillators.
2. "PolyDuo" - 2 voices per device. The first note triggers Oscillator 1 of the device index 1, then Oscillator 2 of device index 1, then Oscillator 1 of device index 2, then Oscillator 2 of device index 2, and so on.

"PolyMono" will simply increase number of voices for "Mono" mode.
"PolyDuo" will increase number of voices for "Duo" mode.

I will restock the synth soon, and looking forward your video!

**Comment by GregCashin** [comment]
Now I'm really glad I asked, I set it up properly and it plays much better!!!! And what you said makes perfect sense with two devices (and is also exactly what I would want for polyphonic settings).

Thank you!

**Comment by GregCashin** [comment]
I ordered a second QUN!

And I have another question; why is using more than 2 devices experimental at this stage? In case I want 6/8 voices!

**Comment by raspy135** [comment]
Thank you for the order.
Three devices work. I said it is experimental because I don't test the configuration very well. So far I don't see issues.
To avoid ground loop noise, I recommend to use different power supply for each device.
