### ISSUE TITLE
Configuration for flashing to bare ESP32-LyraT

### ISSUE THREAD

**Issue by IrregularShed** [raspy135/Qun-synthesizer#16]
Hi!

As I mentioned in #13 I'd like to build a Qun myself on a breadboard. I've now found my ESP32-LyraT board so I thought I'd try flashing the firmware to it.

The firmware has to be flashed to 0x230000, so the bootloader etc will be in 0x00 to 0x22ffff, but there's no information about the partitions or .bin files to create them, nor a combined .bin that could be flashed in place. Would it be possible to get what is necessary to build everything somehow?

Incidentally, I made the assumption that the DIP switches are set for JTAG instead of the SD Card, instead of the default setup.

Thanks

Steve

**Comment by raspy135** [comment]
Hi,
I thought you already have Qun synthesizer.
To be clear, the software is not free, the firmware needs license data to activate.
As you know the software makes the synth unique, not by the hardware.

Technically I can sell only the software part and give you basic instruction, but it would require a good knowledge of ESP32 architecture and it is outside of standard support. So unless you are very interested in building the synth from scratch, I don't recommend the way.

I may be able to send you an unassembled (or partially assembled) version if you want to do some experimental things like using different buttons.

**Comment by IrregularShed** [comment]
Ah, I misread the situation. This project came up in the top three results when I searched Google for "open source esp32 synth" and the link to Github, together with the schematics in the repository, made me assume that the project was completely open. (I'm not alone, it's in the headline of [this GearNews article](https://www.gearnews.com/qun-pocket-synthesizer-analog-modelling-and-open-source/) as well!)
![misleading search result :(](https://user-images.githubusercontent.com/190127/109959346-401b1500-7cdf-11eb-818f-aabd27b1ff0e.png)
I've not been able to work since contracting Covid-19 last year, because it hit my cognitive skills hard and it's difficult being a software developer when you can't comprehend what you were doing four months ago (and I certainly can't charge clients for my time staring at my own code) so I've been trying to work with open source synth projects to kickstart my brain a bit (see for example https://github.com/IrregularShed/groovesizer-tb2-quartet) and had hoped Qun could've joined it because the granular engine sounds lovely and clean.

Since the UK (stupidly) left the European Union the cost of importing things has made it financially impractical (it adds 20% to the cost of the product and the shipping combined, and then handling costs starting around £15/$20 on top of that), so the offer is appreciated but given my circumstances I'll have to decline 😞

**Comment by raspy135** [comment]
Sorry about the misunderstanding. I spent a lot of time to build the software so it cannot be free.

It sounds like you have skills.

Under the hood, I use the library called ESP-ADF.
https://github.com/espressif/esp-adf

It is a convenient library to make DSP applications.
It a long way to build everything, but making a simple synthesizer shouldn't take long.
Qun's board layout and schematic can be a hint to make a similar interface. (Hardware part is opensource).

Shipping to UK/EU area is a real problem. I'm looking for a solution.
