### ISSUE TITLE
How to use arpeggiator?

### ISSUE THREAD

**Issue by GregCashin** [raspy135/Qun-synthesizer#17]
Other than turning it on and selecting a sequence (1111, 2-2-2222, that sort of thing) I'm not sure how to use it, and it doesn't seem to be having an effect on my sequence (or on keys played over midi).

On another note, could the QUN support MIDI aftertouch?

Thanks,
Greg

**Comment by raspy135** [comment]
Hi,
It works for the built-in sequencer, not for the external MIDI signal. (I guess most MIDI keyboards have their own arpeggiator?)

Qun doesn't support MIDI aftertouch at this point. 
It should not be hard to support, but UI is full, I don't see a room to put the setting. I will see if I can find a room for it.

**Comment by GregCashin** [comment]
Got it. I see what it is doing now, I programmed a sequence with all steps on the same note, arp adds or subtracts from what is already tuned in (I was thinking it might effect the note on/off). 1111 goes up 1 semitone each step for 4 steps then cycles again from bottom, 1111-1-1-1-1 goes up one semitone 4 times then down one semitone (-1) 4 times. 2 = two semitones etc. Definitely nice for getting quick easy patterns in!

Honestly there are already so many features it is incredible, and I don't know how long you plan to continue adding on features, but if you can add aftertouch I think it would be a good selling point! In my experience it's usually a feature only found in expensive synths, and I think it would be pretty impressive to see it in the QUN. I love using aftertouch for adding expression and generating new ideas, and with the flexible routing already in the QUN it would be a really nice fit.

**Comment by raspy135** [comment]
Arpeggiator follows the scale/key setting under SEQ CONFIG menu. Default scale is chromatic. Result would be more musical with setting proper scale.

Aftertouch is similar to MIDI CC so no technical challenges.
The problem of adding the feature is more about UI design. Aftertouch needs configuration menu.,
However I don't want to put more menus, I may remove one setting if I add it. 
I will add the feature if I can figure out the way to configure it.

**Comment by GregCashin** [comment]
Even better, I'll try that.

And I see your problem, could the configuration be over MIDI CC only? (I think that is what you did with mod wheel).

Or maybe remove pitch bend range from the menu, replace with aftertouch, and make pitch bend controlled by MIDI CC only? I think mod, pitch bend, and aftertouch can only be used over MIDI anyway right?

**Comment by raspy135** [comment]
Pitch bend is my favorite!! Try crazy wide range for it, it is fun :)

One way I can think to utilize aftertouch is using MIDI learning mode (long pressing any button to enter).
Aftertouch will be assigned when you enter MIDI learning mode and pressing your keyboard deeper. The setting won't be saved.

> I think mod, pitch bend, and aftertouch can only be used over MIDI anyway right?

yes.

**Comment by GregCashin** [comment]
MIDI learning would be perfect (for quick assignment of knobs as well if that was part of it)! I'm sure whatever you decide it will be great!

Bending the pitch all the way down to clicks doesn't ever get old!!!! And I suppose a lot of keyboards don't have aftertouch, so more people would probably use the bend range.

I hope you don't mind me throwing all these thoughts at you, obviously you know what you are doing!

**Comment by raspy135** [comment]
Just to make sure, MIDI learning is already implemented https://github.com/raspy135/Qun-synthesizer#temporary-midi-cc-override
but it doesn't sense aftertouch at this point.

**Comment by GregCashin** [comment]
Ah, I didn't see that,I was just programming through my keyboard, awesome!

I learn something every time I message you!

**Comment by GregCashin** [comment]
WOW, I just realized you can use any external synth as a second/third voice in PolyMono/PolyDuo through the MIDI out. You have designed an incredible machine here....

Is there any way to set it up so that only the third note played sends MIDI out? The external synth (Korg NTS-1) is tracking the first two keys I press, but once I hold those I can play the NTS-1 alone as a third voice.

This is a ridiculously powerful feature, could it also work chained behind two QUN's? Or three?

**Comment by raspy135** [comment]
The feature is to chain multiple Qun's. See https://github.com/raspy135/Qun-synthesizer#polyphonic-setup
Qun has a feature to ignore specific order of notes by setting Device Index in Setting menu.
Technically you can chain 4 Quns to make 8 voices. But I say setting up multiple power source would be pain so normally I just use two to make it 4 voices synth.
All MIDI CC will be synched with PolyMono/PolyDuo mode. In case of unsynchronized for some reason, you can resync by pressing "Rec" button on Lyrat board. It will dump all parameters. This can be used as preset dump as well if you record it to DAW.

**Comment by raspy135** [comment]
This is polyphonic demo
https://www.youtube.com/watch?v=9TAmmh1Cao0
