### ISSUE TITLE
Saving presets: MIDI CC clip changing parameters when exporting from ableton

### ISSUE THREAD

**Issue by GregCashin** [raspy135/Qun-synthesizer#18]
Not sure if you are familiar with ableton, but the issue I'm having is I can record a midi CC clip, and play it back in to the QUN, and it works fine, saves all preset parameters, sounds perfect. I can save the ENTIRE ableton set, reload and play the MIDI CC clip again, forwarding it to the QUN, works great.

BUT if I export the MIDI CC clip as .mid file (in ableton), then load it back up in ableton and send it to the QUN, it sounds way off, and a bunch of parameters have shifted. Any idea what might cause this?

Here is an example, the clip in the ableton file and the .mid should be the same, but they are not.
[Archive.zip](https://github.com/raspy135/Qun-synthesizer/files/6105813/Archive.zip)

I want to share my presets!

**Comment by GregCashin** [comment]
I'm going to ask on the ableton subreddit as well, seems like some kind of ableton setting I'm missing maybe...

**Comment by GregCashin** [comment]
I double checked and the MIDI CC clip in the ableton set, and the .mid file exported from ableton both have the correct MIDI CC information relating to the parameters, but only the clip in the ableton set will play the MIDI information into the QUN properly. 

If you have ableton, can you confirm that? The proper preset (played from the full ableton set) is a synth brass type sound, the test.mid file seems to sound different every time I import it to ableton.

I can also make a video showing you, but again I don't know if you can help here as it seems like an ableton issue.

**Comment by GregCashin** [comment]
Ableton is the issue, sorry if I wasted your time.

Recorded the MIDI CC dump into Reaper, exported the .mid file to my computer, reloaded in reaper and routed it to the QUN, and it worked perfectly. I tried the exact same .mid file (recorded from reaper) in ableton and it didn't work. I was having the same issue with your presets, they just don't load properly through ableton (live 10 lite at least), but perfectly in reaper.

Here is my working Bladerunner Brass Patch! More to come!
[BladerunnerBrass.mid.zip](https://github.com/raspy135/Qun-synthesizer/files/6106430/BladerunnerBrass.mid.zip)

**Comment by GregCashin** [comment]
Demo

[BladerunnerBrass.mp3.zip](https://github.com/raspy135/Qun-synthesizer/files/6106521/BladerunnerBrass.mp3.zip)


Edit: this demo sucks, I will update it tomorrow plus more patches

**Comment by raspy135** [comment]
Hi Greg,

I'm not 100% sure about the root cause, however, I know Live tries to save number of MIDI messages.
Live remembers the last CC value it sent. If the value is not changed (from Live point of view), then Live omits the CC messages.
I searched a lot to fix the issue but so far there is no great way to fix it.
For the workaround, when you rewind the song, then Live will reset the internally-stored CC values.

I save/load .mid file and I don't see the issues specific to .mid file with Live. I hope the tips help.

**Comment by raspy135** [comment]
And thank you for the patch, I will check it when I have a time!
