### ISSUE TITLE
QUN patches

### ISSUE THREAD

**Issue by GregCashin** [raspy135/Qun-synthesizer#19]
[QUN presets:demos.zip](https://github.com/raspy135/Qun-synthesizer/files/6119727/QUN.presets.demos.zip)

Feel free to add any that you like to the repository!

Had a ton of fun making these! I always feel like I have to say it, this thing is an absolute beast, and you are brilliant for creating it.

Can't wait for my second one!

**Comment by GregCashin** [comment]
Violin and Vintage Keys are also polyphonic, forgot to label them

**Comment by GregCashin** [comment]
Probably obvious, but no external effects on demos, only QUN

**Comment by GregCashin** [comment]
Mellotron Pads also poly.

**Comment by GaryHeayes** [comment]
Thanks for sharing your patches, Greg.  Cool sounds... Fine work!
