### ISSUE TITLE
Is there a way to make envelopes re-trigger from zero for every key press?

### ISSUE THREAD

**Issue by GregCashin** [raspy135/Qun-synthesizer#20]
It is an issue when I play legato for something like the flute patch I posted, there is no attack so it no longer sounds flutey. This is the lesser of the two issues, I can get around this by making sure I lift my fingers between key presses, but if I try to play quickly some times it happens accidentally, and it would be nice to be able to play legato without affecting the attack. On the other hand sometimes I really like the legato sound, like with lead patches, so it would be nice to have both.

Where it becomes a bigger issue for me is when I want a long attack and long release for a pad sound. Even if I lift my fingers between keypresses the attack envelope seems to begin/go back up from where the release envelope finished/was when the second keypress occurs. So if the release hasn't reached zero the attack won't start from zero, and if it is right after releasing the first note there is virtually no attack. This means I can't have any release if I want to play back-to-back notes with a long attacks starting from zero (or any attack in some cases).

So it feels like it's always in legato, even when the keys aren't pressed at the same time. I might very well be missing the setting to change this, and I may be misinterpreting what I am hearing, let me know!!

Thank you for your continued support!
Greg

**Comment by GregCashin** [comment]
I also have a question about the envelope polarity inverter switch, I'm not hearing any difference when I turn on/off the Env 1/2 Inv SW. From an init patch I am adjusting the ADSR of ENV 1 while turning Env 1 Inv SW on and off. Also tried with Env 2, and routing it to the the filter cutoff. Is there something else I need to enable?

**Comment by raspy135** [comment]
Hi Greg,

Sorry about the late reply. This is how the envelope works in Qun because that's my preferred way to behave.
Probably I should make the switch to change the behavior.

Polarity switch works only with certain parameters which have positive and negative, such as MOD TUNE. VCF MOD CUTOFF is one of this so it should work. You need to set cutoff somewhere in middle.
If the polarity is default, cutoff feq goes higher when ENV is engaged. If the polarity is inverted, cutoff freq goes lower.

**Comment by GregCashin** [comment]
No problem, I hope you are well!

I wanted to make sure I was using the envelopes correctly, I completely respect your decision to make it behave that way.

I was able to use the polarity switch following your instructions.

Thank you again for your support,
Greg
