### ISSUE TITLE
Granular synthesizer not recording from internal mic

### ISSUE THREAD

**Issue by Audiomoss** [raspy135/Qun-synthesizer#21]
I recently picked up the Qun Synth and could not contact Nunomo as their email is down and no reply on social media. Figured I might be luckier here. The granular synth on the Quun does not record from internal mic. I'm only able to record audio to line in but only get faint noise when trying to record from internal mic. I couldn't find any documentation pointing on any needed configuration to get the mic recording besides just going into granular mode and pressing record.

**Comment by raspy135** [comment]
Hi, sorry for your inconvenience, I lost nunomo.com domain recently. I'm working on it but it would not be easy to recover.

About your question, check System (Setting->System) menu's button 1. https://github.com/raspy135/Qun-synthesizer#setsystem
Set AUX to MIC(2CH). This routes AUX input from the internal microphone.
The mic gain can be adjusted at Mix->"AUX In Gain".
Then Switch to Granular mode, you should be able to hear sound when you make some noise.

**Comment by Audiomoss** [comment]
Aw man sorry to hear you lost the domain name! Glad to hear you're still
around, will definitely try that as soon as I can.

Thanks!

**Comment by raspy135** [comment]
I secured nunomo.net and store is active, but email is not recovered yet.

**Comment by Audiomoss** [comment]
Good luck! I hope you get it sorted out!

Apologies if this is obvious and I’m not seeing it but I’m having a hard time accessing the System settings, I keep getting stuck in the Load Bank section. 

I;’m not able to locate the  below:

System Setting is the setting that is not included in the patch setting. To change the parameter, press the one of 8 buttons and rotate the dial.

**Comment by raspy135** [comment]
To enter System menu, please follow the instruction:

1. Press "Set" button on the base board (It shows "load Bnk1" if it is the first time to enter)
2. Press "MODE" button on the red board, keep pressing it, and turn the dial to clockwise to the end.

Play and Param mode also have more than 8 menus, you need to do this when you want to access more than 9th menu.
