### ISSUE TITLE
What does MOD MODE do?

### ISSUE THREAD

**Issue by GregCashin** [raspy135/Qun-synthesizer#23]
Modulation mode. OSC1 and OSC2 (Pulse Width), OSC1 only, OSC2 only, or VCF's cutoff.

What does switching between these change, and how is it meant to be implemented/used?

Thank you!

Greg

**Comment by GregCashin** [comment]
Also in the SEQ PLAY menu it says: Stop playback or Adjust recording volume by rotating dial. / Next track when not playing / Long press to delete whole recording.

What is the the key combo required to adjust recording volume? Holding stop and turning the knob seems to change the track but I don't see any indication recording volume is changing.

**Comment by GregCashin** [comment]
One other question, you mention this in the envelope section:

PRM:ENV1/2
The synth has four Envelope generators. ENV1 and ENV2 are both independently and fully configurable. ENV3 and ENV4 shares the parameter. Also ENV3 / ENV4 is connected to FM operators. ENV1 and ENV2 are grouped to first voice with Duo mode. ENV3 and ENV4 are grouped to second voice with Duo mode.

I may be misunderstanding something but my experience is that in Duo mode ENV1/3 are grouped to the first voice and ENV2/4 are grouped to the second.

**Comment by raspy135** [comment]
Hi Greg,

I'm on vacation now, so I don't have access to the synth. MOD mode defines the behavior with mod wheel signal from midi keyboard. Default will change PWM of oscillators. You can change it the assignment.

**Comment by raspy135** [comment]
I need to check with the synth to answer the second question. For the third question, you are right, I will correct the manual when I am back.

**Comment by GregCashin** [comment]
Thank you for the response, but get back to enjoying your vacation!

About the second question, I can adjust the recording volume from the Mixer section using button 7 and the dial, perhaps you removed the other shortcut in favour of this easier one.
