### ISSUE TITLE
Possible replacement screen?

### ISSUE THREAD

**Issue by GaryHeayes** [raspy135/Qun-synthesizer#26]
Hi, I'm loving the little Qun and having fun trying out all the features, but my poor old eyes are struggling sometimes with the little screen. It looks like the screen module could be pulled off from the top panel, and maybe replaced...?  I wonder if there's an alternate screen I could buy eg from Adafruit or somewhere else that would work without any software changes.  Do you think that might work? Can you recommend any suitable modules?

**Comment by raspy135** [comment]
The replacement display has to be 128x32 controlled by SSD1306.
I searched a bit.
It looks like https://www.ebay.com/itm/114909594162?hash=item1ac1254232:g:StQAAOSw5FthAFnR
may (or may not) work. Nothing is guaranteed, For example, I2C Device ID is different, it won't work.

It should have VCC, SDA, SCL and GND.

**Comment by GaryHeayes** [comment]
Thanks for the details and your suggestion, Raspy.  I take your point about the risks.  Understood, and thanks.

**Comment by GaryHeayes** [comment]
Hi Raspy135, 
For the time being I found a very low-tech solution!  I got a 'bar loupe' like [this](https://www.ebay.com/itm/113691024858?hash=item1a78835dda:g:07AAAOSwYaFWgrdS) from the local 100yen shop (dollar store), cut off a one-inch section with a saw, and placed it on top of the screen. Instant 2x magnification!
