### ISSUE TITLE
Firmware update failure

### ISSUE THREAD

**Issue by nahly790** [raspy135/Qun-synthesizer#30]
my qun-mk1 starts continuous sound when I try to upgrade to v230 upwards. the sound is coming from OSC1, only right channel.  I can change waves, octaves, LFO tune but can not change volume or stop the sound. I can load presets but then it continues with that preset sound. roll back to v220 and it's fixed. ???
![スクリーンショット (1)](https://github.com/raspy135/Qun-synthesizer/assets/158579727/ea24467a-d3f3-4ea2-ba4c-93106ff9a6df)

**Comment by raspy135** [comment]
Maybe it's related to Send And Return feature. Can you check this setting and make sure this is off?

**Comment by nahly790** [comment]
thankyou  for the reply. sorry but I can't find the setting, maybe I'm missing but I don't see it in the manual either. is it Mixer menu B8?

**Comment by nahly790** [comment]
ok, so I found it in the manual, system menu long press B1. I tryed but long press don't seem to change anything, at least nothing on the display ??

**Comment by raspy135** [comment]
Long press B1 and  you should see "S&R:Off" message with the latest version of the firmware.

**Comment by nahly790** [comment]
hooray!! sorted, thankyou so much!! I'm having sooo much fun with Qun Mk1 and 2!!
