### ISSUE TITLE
Removing .DS_Store files

### ISSUE THREAD

**Issue by HammyHavoc** [raspy135/Qun-synthesizer#5]
Hello Ryan!

You can learn about removing and ignoring .DS_Store files from the repository by following the guide [here](https://code.likeagirl.io/how-to-get-rid-of-ds-store-and-node-modules-in-git-repositories-d37b8a391247).

Not a major priority, but keeps the repository clean and more understandable for newbies. :- )

**Comment by raspy135** [comment]
Thanks, I removed all .DS_Store files.
