### ISSUE TITLE
'VCF Volume: (72)' in documentation actually controls FM FREQ SNAP according to Qun synth; MIDI CC 11 makes Qun stop responding to MIDI CCs

### ISSUE THREAD

**Issue by HammyHavoc** [raspy135/Qun-synthesizer#7]
Hello Ryan!

Stumbled upon a couple of oddities: the readme states that 'VCF Volume: (72)' aka MIDI CC 72 should be manipulating the VCF Volume, instead the Qun synth screen reads 'FM FREQ SNAP'.

Onto the second oddity: when referencing the list below the mention of 'VCF Volume: (72)' in the readme file, I see that MIDI CC 11 is in fact VCF Volume. When I send MIDI CC 11 to the Qun, it works for a brief second, updates the screen on the Qun to display 'VCF VOLUME', but it then freezes and the power needs to be cycled for it to respond to MIDI CCs again.

Holding down the 'Rec' button does make it responsive to the hardware buttons on the Qun itself, and updates the screen, but it doesn't respond to MIDI CCs again until it is power cycled. Even cycling MIDI RECV from ON to OFF doesn't affect it; needs to be power cycled, aka pulling the power cable out and plugging it back in.

This is on v1.43 firmware. :- ) Let me know if you need me to troubleshoot further!

**Comment by raspy135** [comment]
Hi Hammy,

1. FM FREQ SNAP should be 74(0x48). VCF volume is 90(0x5a) or 11(0xb). I will fix the document soon.

2. For the MIDI receiving error, could you try with 1.47? I tested it but it just worked. It sounds the root cause is something different, possibly related to MIDI decoding? Is it wired connection?

**Comment by HammyHavoc** [comment]
Just a quick confidence check:

I've reflashed the LyraT twice via the ESP32 Download Tool, and get a successful 'SYNC' and 'FINISH' (all green labels!), and I reboot the Qun and still see 1.43 instead of 1.47, despite using the 1.47 bin file from the repository. Should I still be seeing 1.43?

When I upgraded the firmware initially, the version number updated; did you remember to bump up the version number on the file?

Re the MIDI receiving error, it's a wired MIDI DIN to 3.5mm TRS cable from a Roland Octa-Capture. All the other CCs I've tried so far work fine, just that one that gives me an issue.

**Comment by HammyHavoc** [comment]
Have just tested it after flashing (despite it still saying 1.43) and can confirm that the troublesome MIDI CC 11 now works perfectly. :- )

**Comment by raspy135** [comment]
The version number is part of the firmware.
It is impossible you upgrade the firmware without changing indicated version number. I'm not sure what happened, but basically if you don't see the new version number, it means firmware update is failed.

Could you check the following things:

- You use two cables (one is for POWER, another one is for UART).
- Double check the starting address (0x230000). (I suspect this is wrong?)
- Disconnect all MIDI IN/OUT cables when you do firmware update.

Address number is very important, if you could overwrite license information if you put wrong number.

Roland is doing something interesting on MIDI signal. I see a lot of processing with UM-ONE.

**Comment by HammyHavoc** [comment]
Using the same, still connected setup from last night:

- No MIDI cables connected
- One tested, functioning micro USB cable for power
- One tested, functioning micro USB cable that you sent with the Qun for the UART port
- Go through the Boot, RST procedure to get the Qun into firmware upload mode
- COM port identified in Device Manager
- ESP32 Download Tool launched, and a successful connection is made (I've seen the unsuccessful message prior to being successful in previous and current firmware flashing attempts)
- Address is right as per your comment and the firmware readme file (it's stored in the software from the first successful firmware update I did when the Qun arrived)
- Correct bin file selected
- Correct COM port selected
- Correct flash size, BAUD rate, SPI speed and SPI mode selected

Detected info is as follows:
> flash vendor:
>20h : N/A
>flash devID:
>4016h
>QUAD;32Mbit
>crystal:
>40 Mhz

- Download started, download finished successfully

Additional info:

>AP:  240AC4E059C1  STA:  240AC4E059C0
>BT:  240AC4E059C2  ETHERNET:  240AC4E059C3

Despite the seemingly successful flash, the firmware version number remains the same.

**Comment by HammyHavoc** [comment]
Found the problem! I'll update the firmware documentation with the solution.

![image](https://user-images.githubusercontent.com/503951/90315379-f6213c00-df12-11ea-9a87-85cada25b613.png)
This checkbox on the left unticked after closing and reopening the ESP32 Download Tool. Now it says 1.47! :- )

**Comment by raspy135** [comment]
It's good to know. I will update the document.
BTW I'm using Python (esptools) for the update. 
Once you installed the software, the option is easier. I don't recommend this normally but you should be fine with it.
