### ISSUE TITLE
Firmware update takes a long time

### ISSUE THREAD

**Issue by thisfred** [raspy135/Qun-synthesizer#9]
Not sure if this is a bug or not, but I downloaded the latest version of the firmware (v163), and followed all the steps (for windows). There is a little square blinking on the Qun, and the Flash Download Tool console shows progress (a seemingly endless stream of `....._____....._____`), but it's been about 20 minutes now, which seems like a very long time. Not sure what to do. Is it safe to reboot/disconnect at this point, and try again?

**Comment by raspy135** [comment]
Hi, first of all, it is safe to try again.
...._____....._____ means your device is not in firmware update mode.
Press "Boot" button and "RST" button on ESP32-LyraT board, keep pressing it, then release "RST" button only, then release "Boot" button. Now it should be firmware uploading mode. (There is no UI feedback or indication)
It's Japanese video but this Youtube video might help how to press the buttons.
https://www.youtube.com/watch?v=GGn-agl8hng&feature=emb_logo

**Comment by thisfred** [comment]
Thank you! I must have released them in the wrong order, it's working now!
